### ISSUE TITLE
I have a problem 

### ISSUE THREAD

**Issue by Rkso0** [thisismy-github/instant-replay-suite#1]
sorry but I am a noob in programming so I have this message when I clicked the exe.file 
![image](https://user-images.githubusercontent.com/121486109/227680655-1f2a6aa3-21fb-4479-baaa-67acd048beff.png)

- I download all requirements
- Windows 10 
 
edit: I wish you write full guide for noobs like me \:

**Comment by thisismy-github** [comment]
What hotkey do you normally use for instant replays? Also, does the program work if you set `INSTANT_REPLAY_HOTKEY_OVERRIDE` in the `config.settings.ini` file?

**Comment by Rkso0** [comment]
oh thanks, I forgot the hotkey 
it is working now
